plot0:
    number_plots: one
    plot_name: p0_one_set_one_run_timeseries.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None

plot01:
    number_plots: one
    plot_name: p01_one_set_multiple_runs_timeseries.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None

plot02:
    number_plots: one
    plot_name: p02_multi_set_multiple_runs_timeseries.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None

plot1:
    number_plots: one
    plot_name: p1_one_set_one_run_timeseries.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None

plot11:
    number_plots: one
    plot_name: p11_one_set_multiple_runs_timeseries.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None

plot12:
    number_plots: one
    plot_name: p12_multi_set_multiple_runs_timeseries.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None

plot20:
    number_plots: one
    plot_name: p2_one_set_one_runs_2_vars_ts_quantile.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: y(t)
    linestyle: solid
    marker: None
    fill_between: yes
    fillcolor: red

    
plot21:
    number_plots: one
    plot_name: p21_one_set_one_runs_1_var_ts_quantile.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: y(t)
    linestyle: solid
    marker: None
    fill_between: yes
    fillcolor: red

plot22:
    number_plots: one
    plot_name: p22_one_set_multiple_runs_ts_quantile.png
    plot_legend: no
    legend_location: best
    xaxis_label: Time
    yaxis_label: y(t)
    linestyle: solid
    marker: None
    fill_between: yes
    fillcolor: red

plot23:
    number_plots: one
    plot_name: p23_multi_set_multiple_runs_ts_quantile.png
    plot_legend: no
    legend_location: best
    xaxis_label: Time
    yaxis_label: y(t)
    linestyle: solid
    marker: None
    fill_between: yes
    fillcolor: red
    
    
plot3:
    number_plots: one
    plot_name: p3_ts_multibatch_analysis_one_plot.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: y(t)
    linestyle: solid
    marker: None
    fill_between: yes
    fillcolor: darkgreen

plot30:
    number_plots: many
    plot_name: p30_ts_multibatch_analysis_many_plots.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: y(t)
    linestyle: solid
    marker: None
    fill_between: yes
    fillcolor: darkgreen

plot31:
    number_plots: one
    plot_name: p31_ts_multiset_analysis.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: y(t)
    linestyle: solid
    marker: None
    fill_between: yes
    fillcolor: darkgreen

plot4:
   number_plots: one
   plot_name: p4_ts_agent_analysis_one_set_one_run.png
   plot_legend: yes
   legend_location: best
   xaxis_label: Time
   yaxis_label: price
   linestyle: solid
   marker: None
   greyscale: False

plot41:
   number_plots: one
   plot_name: p41_ts_agent_analysis_multi_set_multi_run.png
   plot_legend: no
   legend_location: best
   xaxis_label: Time
   yaxis_label: price
   linestyle: solid
   marker: None
   greyscale: False
   
plot5:
    number_plots: one
    plot_name: p5_one_set_one_run_bp_price.png
    plot_legend: yes
    legend_label: (Agent = Firm, var = Price)
    legend_location: best
    xaxis_label: Time
    yaxis_label: Distribution over price
    number_bars: 5
    greyscale: True

plot6:
    number_plots: one
    plot_name: p6_one_set_multiple_runs_sp_price_output.png
    plot_legend: yes
    legend_location: best
    legend_label: price vs. output
    linestyle: solid
    marker: +

plot7:
    number_plots: one
    plot_name: p7_one_set_agent_sp_price_delay.png
    plot_legend: no
    legend_location: best
    legend_label: price delay vs. price
    marker: +

plot8:
    number_plots: one
    plot_name: p8_one_set_multiple_runs_sp_price_delay.png
    plot_legend: yes
    legend_location: best
    legend_label: price delay vs. price
    linestyle: solid
    marker: o

plot9:
    number_plots: one
    plot_name: p9_one_set_one_run_hg_price.png
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: bar
    plot_legend: yes
    fill: yes
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel

plot10:
    number_plots: one
    plot_name: p10_one_set_multiple_runs_hg_price.png
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: bar
    plot_legend: yes
    fill: yes
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel

plot11:
    number_plots: one
    plot_name: p11_one_set_multiple_runs_hg_price.png
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: bar
    plot_legend: yes
    fill: yes
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel

plot12:
    number_plots: one
    plot_name: p12_two_sets_multiple_runs_hg_price.png
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: step
    plot_legend: yes
    fill: no
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel
