i/o:
    # set up the name of the root folder from repository
    repo_name: 'FLAViz'

    # set up your input_path for the resulting plots, it's relative unless it starts with a '/'
    input_path: 'data/visualisation'

    #from main folder
    #input_path: '../../data/visualisation'

    #from config folder:
    #input_path: '../../../data/visualisation'

    #hard-coded:
    #input_path: '/media/sander/DataStorage1/GIT/GitHub/FLAViz@svdhoog/FLAViz/data/visualisation'

    # set up your output_path for the resulting plots, it's relative unless it starts with a '/'
    output_path: 'results'

    #from main folder
    #output_path: '../../results_test'

    #from config folder:
    #output_path: '../../../results_test2'

    #hard-coded:
    #output_path: '/media/sander/DataStorage1/GIT/GitHub/FLAViz@svdhoog/FLAViz/results_test3'

    input_files:
        CentralBank: CentralBank.h5 # please name the key as the agent name
        Eurostat: Eurostat.h5
        Firm: Firm.h5

plot1:
    timeseries:
        agent: Firm
        analysis: multiple_run
        variables:
            var1: [price]
        set: [13]
        run: [range,[1,10]]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: median

plot2:
    timeseries:
        agent: Firm
        analysis: multiple_run
        variables:
            var1: [price]
            var2: [total_debt]
        set: [10]
        run: [1]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: custom_quantile
        quantile_values:
            lower_percentile : 0.20
            upper_percentile : 0.80

plot3:
    timeseries:
        agent: Firm
        analysis: multiple_batch
        variables:
            var1: [price,total_debt,technology]
        set: [10,13,16,17]
        run: [range,[1,20]]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: custom_quantile
        quantile_values:
            lower_percentile : 0.20
            upper_percentile : 0.80

plot4:
   timeseries:
       agent: Firm
       analysis: agent
       variables:
           var1: [price]
       set: [13]
       run: [1]
       major: [range,[6020,12500,20]]
       minor: [range,[1,20]]
       summary: mean

plot5:
    boxplot:
        agent: Firm
        analysis: multiple_set
        variables:
            var1: [price]
        set: [13]
        run: [1]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: full

plot6:
  scatterplot:
        agent: Firm
        analysis: multiple_batch
        variables:
            var1: [price]
            var2: [output]
        delay: no
        set: [13]
        run: [range,[1,2]]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: mean

plot61:
  scatterplot:
        agent: Firm
        analysis: multiple_batch
        variables:
            var1: [price]
            var2: [output]
        delay: no
        set: [13]
        run: [range,[1,2]]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: mean

plot7:
    scatterplot:
        agent: Firm
        analysis: agent
        variables:
            var1: [price]
        delay: yes
        set: [13]
        run: [range,[1,20]]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: full

plot8:
    scatterplot:
        agent: Firm
        analysis: multiple_batch
        variables:
            var1: [price]
        delay: yes
        set: [13]
        run: [range,[1,20]]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: mean

plot9:
    histogram:
        agent: Firm
        analysis: multiple_run
        variables:
            var1: [price]
        set: [10]
        run: [1]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: mean

plot10:
    histogram:
        agent: Firm
        analysis: multiple_batch
        variables:
            var1: [price]
        set: [10]
        run: [range,[1,20]]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: mean    # Note: the summary is mean value, over each level, gives hist of distribution of means

plot11:
    histogram:
        agent: Firm
        analysis: multiple_batch
        variables:
            var1: [price]
        set: [10]
        run: [range,[1,20]]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: full  # Note: here the histogram is over the entire distribution

plot12:
    histogram:
        agent: Firm
        analysis: multiple_batch
        variables:
            var1: [price]
        set: [10, 13]
        run: [range,[1,20]]
        major: [range,[6020,12500,20]]
        minor: [range,[1,80]]
        summary: mean
